services:
  postgres:
    image: postgres:16
    container_name: aevor-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: aevor
      POSTGRES_PASSWORD: aevor
      POSTGRES_DB: aevor

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: